environment: ollie-t30

nameOverride: "blogifier-ollie"
fullnameOverride: "blogifier-ollie"

dnsName: ollie.leenet.link

image:
  repository: 192.168.1.151:32000/blogifier

gatewayNamespace: default
gateway: default/leenet-gateway
appNamespace: default