version: '2'

services:

  blogifier:
      image: 192.168.1.151:32000/blogifier:1.11.49
      build:
          context: ./
          dockerfile: ./Dockerfile
      restart: unless-stopped
      ports:
          - "5001:443"
