version: '2'

services:

  blogifier:
      image: neon-registry.d95f-98d9-33df-f8a6.neoncluster.io/leenet/blogifier:1.11.54
      build:
          context: ./
          dockerfile: ./Dockerfile
      restart: unless-stopped
      ports:
          - "5001:443"
