// <auto-generated />
using System;
using Blogifier.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blogifier.Core.Data.Migrations
{
  [DbContext(typeof(AppDbContext))]
  partial class AppDbContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "7.0.5")
          .HasAnnotation("Relational:MaxIdentifierLength", 64);

      modelBuilder.Entity("Blogifier.Shared.Author", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            b.Property<string>("Avatar")
                      .HasMaxLength(400)
                      .HasColumnType("varchar(400)");

            b.Property<string>("Bio")
                      .HasMaxLength(2000)
                      .HasColumnType("varchar(2000)");

            b.Property<int?>("BlogId")
                      .HasColumnType("int");

            b.Property<DateTime>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime(6)");

            b.Property<string>("DisplayName")
                      .IsRequired()
                      .HasMaxLength(160)
                      .HasColumnType("varchar(160)");

            b.Property<string>("Email")
                      .IsRequired()
                      .HasMaxLength(160)
                      .HasColumnType("varchar(160)");

            b.Property<bool>("IsAdmin")
                      .HasColumnType("tinyint(1)");

            b.Property<string>("Password")
                      .IsRequired()
                      .HasMaxLength(160)
                      .HasColumnType("varchar(160)");

            b.HasKey("Id");

            b.HasIndex("BlogId");

            b.ToTable("Authors");
          });

      modelBuilder.Entity("Blogifier.Shared.Blog", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            b.Property<int>("AnalyticsListType")
                      .HasColumnType("int");

            b.Property<int>("AnalyticsPeriod")
                      .HasColumnType("int");

            b.Property<string>("Cover")
                      .HasMaxLength(160)
                      .HasColumnType("varchar(160)");

            b.Property<DateTime>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime(6)");

            b.Property<string>("Description")
                      .IsRequired()
                      .HasMaxLength(450)
                      .HasColumnType("varchar(450)");

            b.Property<string>("FooterScript")
                      .HasMaxLength(2000)
                      .HasColumnType("varchar(2000)");

            b.Property<string>("HeaderScript")
                      .HasMaxLength(2000)
                      .HasColumnType("varchar(2000)");

            b.Property<bool>("IncludeFeatured")
                      .HasColumnType("tinyint(1)");

            b.Property<int>("ItemsPerPage")
                      .HasColumnType("int");

            b.Property<string>("Logo")
                      .HasMaxLength(160)
                      .HasColumnType("varchar(160)");

            b.Property<string>("Theme")
                      .IsRequired()
                      .HasMaxLength(160)
                      .HasColumnType("varchar(160)");

            b.Property<string>("Title")
                      .IsRequired()
                      .HasMaxLength(160)
                      .HasColumnType("varchar(160)");

            b.HasKey("Id");

            b.ToTable("Blogs");
          });

      modelBuilder.Entity("Blogifier.Shared.Category", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            b.Property<string>("Content")
                      .IsRequired()
                      .HasMaxLength(120)
                      .HasColumnType("varchar(120)");

            b.Property<DateTime>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime(6)");

            b.Property<string>("Description")
                      .HasMaxLength(255)
                      .HasColumnType("varchar(255)");

            b.HasKey("Id");

            b.ToTable("Categories");
          });

      modelBuilder.Entity("Blogifier.Shared.MailSetting", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            b.Property<int?>("BlogId")
                      .HasColumnType("int");

            b.Property<DateTime>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime(6)");

            b.Property<bool>("Enabled")
                      .HasColumnType("tinyint(1)");

            b.Property<string>("FromEmail")
                      .IsRequired()
                      .HasMaxLength(120)
                      .HasColumnType("varchar(120)");

            b.Property<string>("FromName")
                      .IsRequired()
                      .HasMaxLength(120)
                      .HasColumnType("varchar(120)");

            b.Property<string>("Host")
                      .IsRequired()
                      .HasMaxLength(160)
                      .HasColumnType("varchar(160)");

            b.Property<int>("Port")
                      .HasColumnType("int");

            b.Property<string>("ToName")
                      .IsRequired()
                      .HasMaxLength(120)
                      .HasColumnType("varchar(120)");

            b.Property<string>("UserEmail")
                      .IsRequired()
                      .HasMaxLength(120)
                      .HasColumnType("varchar(120)");

            b.Property<string>("UserPassword")
                      .IsRequired()
                      .HasMaxLength(120)
                      .HasColumnType("varchar(120)");

            b.HasKey("Id");

            b.HasIndex("BlogId");

            b.ToTable("MailSettings");
          });

      modelBuilder.Entity("Blogifier.Shared.Newsletter", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            b.Property<DateTime>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime(6)");

            b.Property<int>("PostId")
                      .HasColumnType("int");

            b.Property<bool>("Success")
                      .HasColumnType("tinyint(1)");

            b.Property<DateTime>("UpdatedAt")
                      .ValueGeneratedOnAddOrUpdate()
                      .HasColumnType("datetime(6)");

            b.HasKey("Id");

            b.HasIndex("PostId");

            b.ToTable("Newsletters");
          });

      modelBuilder.Entity("Blogifier.Shared.Post", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            b.Property<int>("AuthorId")
                      .HasColumnType("int");

            b.Property<int?>("BlogId")
                      .HasColumnType("int");

            b.Property<string>("Content")
                      .IsRequired()
                      .HasColumnType("longtext");

            b.Property<string>("Cover")
                      .HasMaxLength(160)
                      .HasColumnType("varchar(160)");

            b.Property<DateTime>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime(6)");

            b.Property<string>("Description")
                      .IsRequired()
                      .HasMaxLength(450)
                      .HasColumnType("varchar(450)");

            b.Property<bool>("IsFeatured")
                      .HasColumnType("tinyint(1)");

            b.Property<int>("PostType")
                      .HasColumnType("int");

            b.Property<int>("PostViews")
                      .HasColumnType("int");

            b.Property<DateTime>("Published")
                      .HasColumnType("datetime(6)");

            b.Property<double>("Rating")
                      .HasColumnType("double");

            b.Property<bool>("Selected")
                      .HasColumnType("tinyint(1)");

            b.Property<string>("Slug")
                      .IsRequired()
                      .HasMaxLength(160)
                      .HasColumnType("varchar(160)");

            b.Property<string>("Title")
                      .IsRequired()
                      .HasMaxLength(160)
                      .HasColumnType("varchar(160)");

            b.Property<DateTime>("UpdatedAt")
                      .ValueGeneratedOnAddOrUpdate()
                      .HasColumnType("datetime(6)");

            b.HasKey("Id");

            b.HasIndex("AuthorId");

            b.HasIndex("BlogId");

            b.ToTable("Posts");
          });

      modelBuilder.Entity("Blogifier.Shared.PostCategory", b =>
          {
            b.Property<int>("PostId")
                      .HasColumnType("int");

            b.Property<int>("CategoryId")
                      .HasColumnType("int");

            b.HasKey("PostId", "CategoryId");

            b.HasIndex("CategoryId");

            b.ToTable("PostCategories");
          });

      modelBuilder.Entity("Blogifier.Shared.Storage", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            b.Property<int>("AuthorId")
                      .HasColumnType("int");

            b.Property<string>("ContentType")
                      .IsRequired()
                      .HasMaxLength(128)
                      .HasColumnType("varchar(128)");

            b.Property<DateTime>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime(6)");

            b.Property<DateTime?>("DeletedAt")
                      .HasColumnType("datetime(6)");

            b.Property<bool>("IsDeleted")
                      .HasColumnType("tinyint(1)");

            b.Property<long>("Length")
                      .HasColumnType("bigint");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasMaxLength(256)
                      .HasColumnType("varchar(256)");

            b.Property<string>("Path")
                      .IsRequired()
                      .HasMaxLength(2048)
                      .HasColumnType("varchar(2048)");

            b.Property<int>("StorageType")
                      .HasColumnType("int");

            b.HasKey("Id");

            b.ToTable("Storages");
          });

      modelBuilder.Entity("Blogifier.Shared.Subscriber", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            b.Property<int?>("BlogId")
                      .HasColumnType("int");

            b.Property<string>("Country")
                      .HasMaxLength(120)
                      .HasColumnType("varchar(120)");

            b.Property<DateTime>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime(6)");

            b.Property<string>("Email")
                      .IsRequired()
                      .HasMaxLength(160)
                      .HasColumnType("varchar(160)");

            b.Property<string>("Ip")
                      .HasMaxLength(80)
                      .HasColumnType("varchar(80)");

            b.Property<string>("Region")
                      .HasMaxLength(120)
                      .HasColumnType("varchar(120)");

            b.Property<DateTime>("UpdatedAt")
                      .ValueGeneratedOnAddOrUpdate()
                      .HasColumnType("datetime(6)");

            b.HasKey("Id");

            b.HasIndex("BlogId");

            b.ToTable("Subscribers");
          });

      modelBuilder.Entity("Blogifier.Shared.Author", b =>
          {
            b.HasOne("Blogifier.Shared.Blog", null)
                      .WithMany("Authors")
                      .HasForeignKey("BlogId");
          });

      modelBuilder.Entity("Blogifier.Shared.MailSetting", b =>
          {
            b.HasOne("Blogifier.Shared.Blog", "Blog")
                      .WithMany()
                      .HasForeignKey("BlogId");

            b.Navigation("Blog");
          });

      modelBuilder.Entity("Blogifier.Shared.Newsletter", b =>
          {
            b.HasOne("Blogifier.Shared.Post", "Post")
                      .WithMany()
                      .HasForeignKey("PostId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Post");
          });

      modelBuilder.Entity("Blogifier.Shared.Post", b =>
          {
            b.HasOne("Blogifier.Shared.Author", null)
                      .WithMany("Posts")
                      .HasForeignKey("AuthorId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.HasOne("Blogifier.Shared.Blog", "Blog")
                      .WithMany("Posts")
                      .HasForeignKey("BlogId");

            b.Navigation("Blog");
          });

      modelBuilder.Entity("Blogifier.Shared.PostCategory", b =>
          {
            b.HasOne("Blogifier.Shared.Category", "Category")
                      .WithMany("PostCategories")
                      .HasForeignKey("CategoryId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.HasOne("Blogifier.Shared.Post", "Post")
                      .WithMany("PostCategories")
                      .HasForeignKey("PostId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Category");

            b.Navigation("Post");
          });

      modelBuilder.Entity("Blogifier.Shared.Subscriber", b =>
          {
            b.HasOne("Blogifier.Shared.Blog", "Blog")
                      .WithMany()
                      .HasForeignKey("BlogId");

            b.Navigation("Blog");
          });

      modelBuilder.Entity("Blogifier.Shared.Author", b =>
          {
            b.Navigation("Posts");
          });

      modelBuilder.Entity("Blogifier.Shared.Blog", b =>
          {
            b.Navigation("Authors");

            b.Navigation("Posts");
          });

      modelBuilder.Entity("Blogifier.Shared.Category", b =>
          {
            b.Navigation("PostCategories");
          });

      modelBuilder.Entity("Blogifier.Shared.Post", b =>
          {
            b.Navigation("PostCategories");
          });
#pragma warning restore 612, 618
    }
  }
}
